---
apiVersion: v1
kind: Namespace
metadata:
  name: game-tictactoe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-tictactoe
  name: deployment-tictactoe
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-tictactoe
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-tictactoe
    spec:
      containers:
      - image: forsignup8580/tictactoe:latest
        imagePullPolicy: Always
        name: app-tictactoe
        ports:
        - containerPort: 8080  
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-tictactoe
  name: service-tictactoe
spec:
  ports:
    - port: 80  
      targetPort: 8080  
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-tictactoe
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: game-tictactoe
  name: ingress-tictactoe
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-tictactoe
              port:
                number: 80
